# Ccarga y conteo de datos

In [13]:

import numpy as np
import pandas as pd

import plotly.graph_objects as go


#leer los 5 archivos en la carpeta de Datos cargar y solo la hoja llamada "Datos" de cada uno
df_agrupado = pd.read_excel('Datos/rx fijo Calculadora de dosis HUN 2024 V4 (Autoguardado).xlsm', sheet_name='Datos')
df1 = pd.read_excel('Datos/datos 00 Calculadora de dosis HUN 2024.xlsm', sheet_name='Datos')
df2 = pd.read_excel('Datos/datos 0 Calculadora de dosis HUN 2024 V3.0.xlsm', sheet_name='Datos')
df3 = pd.read_excel('Datos/datos 01 Calculadora de dosis HUN 2024 V3.0.xlsm', sheet_name='Datos')
df4 = pd.read_excel('Datos/fluoro rx Calculadora de dosis HUN 2025 V4.0.xlsm', sheet_name='Datos')
df5 = pd.read_excel('Datos/rx fijo 1 Calculadora de dosis HUN 2025 V4.0.xlsm', sheet_name='Datos')

#imprime el numero de filas de cada df y lo guardamos para compar
num_filas = {
    "df1": len(df1),
    "df2": len(df2),
    "df3": len(df3),
    "df4": len(df4),
}

print("Numero de filas df1:", len(df1))
print("Numero de filas df2:", len(df2))
print("Numero de filas df3:", len(df3))
print("Numero de filas df4:", len(df4))
print("Numero de filas df5:", len(df5))
print("Numero de filas df_agrupado:", len(df_agrupado))

Numero de filas df1: 113
Numero de filas df2: 72
Numero de filas df3: 268
Numero de filas df4: 68
Numero de filas df5: 49
Numero de filas df_agrupado: 1626

In [14]:
#imprime la info() de cada df
print("Info df1:")
print(df1.info())
print("Info df2:")
print(df2.info())
print("Info df3:")
print(df3.info())
print("Info df4:")
print(df4.info())
print("Info df5:")
print(df5.info())
print("Info df_agrupado:")
print(df_agrupado.info())

Info df1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    113 non-null    datetime64[ns]
 1   Estudio                  113 non-null    object
 2   Peso[kg]                 113 non-null    int64
 3   Distancia foco-detector  113 non-null    object
 4   Proyección               113 non-null    object
 5   kV                       113 non-null    int64
 6   mAs                      113 non-null    float64
 7   Img Aprobadas            113 non-null    int64
 8   Img Rechazadas           104 non-null    float64
 9   Dosis [mGy]              113 non-null    float64
 10  Dosis Total [mGy]        56 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(3), object(4)
memory usage: 9.8+ KB
None
Info df2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    71 non-null     datetime64[ns]
 1   Estudio                  71 non-null     object
 2   Peso[kg]                 71 non-null     float64
 3   Distancia foco-detector  71 non-null     object
 4   Proyección               72 non-null     object
 5   kV                       72 non-null     int64
 6   mAs                      72 non-null     float64
 7   Img Aprobadas            72 non-null     int64
 8   Img Rechazadas           72 non-null     int64
 9   Dosis [mGy]              72 non-null     float64
 10  Dosis Total [mGy]        40 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(3)
memory usage: 6.3+ KB
None
Info df3:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    268 non-null    datetime64[ns]
 1   Estudio                  268 non-null    object
 2   Peso[kg]                 268 non-null    int64
 3   Distancia foco-detector  268 non-null    object
 4   Proyección               268 non-null    object
 5   kV                       268 non-null    int64
 6   mAs                      268 non-null    float64
 7   Img Aprobadas            268 non-null    int64
 8   Img Rechazadas           267 non-null    float64
 9   Dosis [mGy]              268 non-null    float64
 10  Dosis Total [mGy]        144 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(3), object(4)
memory usage: 23.2+ KB
None
Info df4:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    68 non-null     datetime64[ns]
 1   Estudio                  68 non-null     object
 2   Peso[kg]                 36 non-null     object
 3   Distancia foco-detector  68 non-null     object
 4   Proyección               68 non-null     object
 5   kV                       68 non-null     int64
 6   mAs                      68 non-null     float64
 7   Img Aprobadas            68 non-null     int64
 8   Img Rechazadas           68 non-null     int64
 9   Dosis [mGy]              68 non-null     float64
 10  Dosis Total [mGy]        38 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 6.0+ KB
None
Info df5:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    49 non-null     datetime64[ns]
 1   Estudio                  49 non-null     object
 2   Peso[kg]                 22 non-null     float64
 3   Distancia foco-detector  49 non-null     object
 4   Proyección               49 non-null     object
 5   kV                       49 non-null     int64
 6   mAs                      49 non-null     float64
 7   Img Aprobadas            49 non-null     int64
 8   Img Rechazadas           49 non-null     int64
 9   Dosis [mGy]              49 non-null     float64
 10  Dosis Total [mGy]        26 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(3)
memory usage: 4.3+ KB
None
Info df_agrupado:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1626 entries, 0 to 1625
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    1488 non-null   datetime64[ns]
 1   Estudio                  1488 non-null   object
 2   Peso[kg]                 1016 non-null   float64
 3   Distancia foco-detector  1491 non-null   object
 4   Proyección               1626 non-null   object
 5   kV                       1626 non-null   float64
 6   mAs                      1626 non-null   float64
 7   Img Aprobadas            1626 non-null   int64
 8   Img Rechazadas           1616 non-null   float64
 9   Dosis [mGy]              1626 non-null   float64
 10  Dosis Total [mGy]        916 non-null    object
dtypes: datetime64[ns](1), float64(5), int64(1), object(4)
memory usage: 139.9+ KB
None

## Econtrando el error de los datos

In [ ]:
df3.info()
df3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    268 non-null    datetime64[ns]
 1   Estudio                  268 non-null    object
 2   Peso[kg]                 268 non-null    int64
 3   Distancia foco-detector  268 non-null    object
 4   Proyección               268 non-null    object
 5   kV                       268 non-null    int64
 6   mAs                      268 non-null    float64
 7   Img Aprobadas            268 non-null    int64
 8   Img Rechazadas           267 non-null    float64
 9   Dosis [mGy]              268 non-null    float64
 10  Dosis Total [mGy]        144 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(3), object(4)
memory usage: 23.2+ KB

In [16]:
# --- 1) Nos quedamos solo con las filas donde 'Dosis Total [mGy]' no es NaN,es decir cada procedimiento unico
df_totales = df3.dropna(subset=["Dosis Total [mGy]"])

# Convertir "Dosis Total [mGy]" a float, reemplazando la coma por punto
# Convertimos todo a string, reemplazamos coma por punto, y luego a float
df_totales["Dosis Total [mGy]"] = (
    df_totales["Dosis Total [mGy]"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2572050912.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
df_totales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144 entries, 1 to 267
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    144 non-null    datetime64[ns]
 1   Estudio                  144 non-null    object
 2   Peso[kg]                 144 non-null    int64
 3   Distancia foco-detector  144 non-null    object
 4   Proyección               144 non-null    object
 5   kV                       144 non-null    int64
 6   mAs                      144 non-null    float64
 7   Img Aprobadas            144 non-null    int64
 8   Img Rechazadas           143 non-null    float64
 9   Dosis [mGy]              144 non-null    float64
 10  Dosis Total [mGy]        144 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(3)
memory usage: 13.5+ KB

# Tratamiento antes de verificacion

In [18]:
#convertimos primero a string y luego a float todos los df de "Dosis Total [mGy]"
df1["Dosis Total [mGy]"] = df1["Dosis Total [mGy]"].astype(str).str.replace(",", ".", regex=False).astype(float)
df2["Dosis Total [mGy]"] = df2["Dosis Total [mGy]"].astype(str).str.replace(",", ".", regex=False).astype(float)
df3["Dosis Total [mGy]"] = df3["Dosis Total [mGy]"].astype(str).str.replace(",", ".", regex=False).astype(float)
df4["Dosis Total [mGy]"] = df4["Dosis Total [mGy]"].astype(str).str.replace(",", ".", regex=False).astype(float)
df5["Dosis Total [mGy]"] = df5["Dosis Total [mGy]"].astype(str).str.replace(",", ".", regex=False).astype(float)
df_agrupado["Dosis Total [mGy]"] = df_agrupado["Dosis Total [mGy]"].astype(str).str.replace(",", ".", regex=False).astype(float)

In [19]:
# Comparar nombres de columnas y tipos de datos entre los DataFrames

# Diccionario con todos los DataFrames a comparar
dfs = {
    "df1": df1,
    "df2": df2,
    "df3": df3,
    "df4": df4,
    "df5": df5,
    "df_agrupado": df_agrupado
}

# Definimos el DataFrame de referencia (estructura "correcta" esperada)
ref_name = "df_agrupado"
ref_cols = list(dfs[ref_name].columns)   # Orden y nombres de columnas de referencia
ref_dtypes = dfs[ref_name].dtypes        # Tipos de datos de referencia

results = []

# Recorremos cada DataFrame y comparamos contra la referencia
for name, d in dfs.items():
    # Columnas que faltan respecto a la referencia
    missing = [c for c in ref_cols if c not in d.columns]
    # Columnas extra que no están en la referencia
    extra = [c for c in d.columns if c not in ref_cols]
    # Verificación de que el orden de columnas coincide exactamente
    order_ok = list(d.columns) == ref_cols
    # Lista de diferencias de tipo de datos (columna, dtype_en_df_actual, dtype_ref)
    dtype_diff = []
    for c in ref_cols:
        if c in d.columns and d[c].dtype != ref_dtypes[c]:
            dtype_diff.append((c, str(d[c].dtype), str(ref_dtypes[c])))

    results.append({
        "df": name,
        "missing_cols": missing,
        "extra_cols": extra,
        "column_order_matches_ref": order_ok,
        "dtype_differences": dtype_diff
    })

# Impresión detallada por DataFrame
for r in results:
    print(f"\n=== {r['df']} ===")
    print("Faltantes:", r["missing_cols"] if r["missing_cols"] else "Ninguno")
    print("Extras:", r["extra_cols"] if r["extra_cols"] else "Ninguno")
    print("Orden igual a ref:", r["column_order_matches_ref"])
    if r["dtype_differences"]:
        print("Diferencias de dtype (col, este_df, ref_df):")
        for diff in r["dtype_differences"]:
            print("  ", diff)
    else:
        print("Sin diferencias de dtype.")

# Resumen consolidado (cuenta de incidencias por DataFrame)
summary = pd.DataFrame([{
    "df": r["df"],
    "faltantes": len(r["missing_cols"]),
    "extras": len(r["extra_cols"]),
    "orden_ok": r["column_order_matches_ref"],
    "dtypes_diff": len(r["dtype_differences"])
} for r in results])

print("\nResumen:")
print(summary)

=== df1 ===

Faltantes: Ninguno
Extras: Ninguno
Orden igual a ref: True
Diferencias de dtype (col, este_df, ref_df):
   ('Peso[kg]', 'int64', 'float64')
   ('kV', 'int64', 'float64')

=== df2 ===
Faltantes: Ninguno
Extras: Ninguno
Orden igual a ref: True
Diferencias de dtype (col, este_df, ref_df):
   ('kV', 'int64', 'float64')
   ('Img Rechazadas', 'int64', 'float64')

=== df3 ===
Faltantes: Ninguno
Extras: Ninguno
Orden igual a ref: True
Diferencias de dtype (col, este_df, ref_df):
   ('Peso[kg]', 'int64', 'float64')
   ('kV', 'int64', 'float64')

=== df4 ===
Faltantes: Ninguno
Extras: Ninguno
Orden igual a ref: True
Diferencias de dtype (col, este_df, ref_df):
   ('Peso[kg]', 'object', 'float64')
   ('kV', 'int64', 'float64')
   ('Img Rechazadas', 'int64', 'float64')

=== df5 ===
Faltantes: Ninguno
Extras: Ninguno
Orden igual a ref: True
Diferencias de dtype (col, este_df, ref_df):
   ('kV', 'int64', 'float64')
   ('Img Rechazadas', 'int64', 'float64')

=== df_agrupado ===
Faltantes: Ninguno
Extras: Ninguno
Orden igual a ref: True
Sin diferencias de dtype.

Resumen:
            df  faltantes  extras  orden_ok  dtypes_diff
0          df1          0       0      True            2
1          df2          0       0      True            2
2          df3          0       0      True            2
3          df4          0       0      True            3
4          df5          0       0      True            2
5  df_agrupado          0       0      True            0

In [20]:
#los que tienen diferencias de tipo dame espesificamente las columnas que son diferentes
for r in results:
    if r["dtype_differences"]:
        print(f"\nDiferencias de tipo en {r['df']}:")
        for col, dtype_df, dtype_ref in r["dtype_differences"]:
            print(f"  Columna: {col}, Tipo en {r['df']}: {dtype_df}, Tipo en referencia: {dtype_ref}")

Diferencias de tipo en df1:
  Columna: Peso[kg], Tipo en df1: int64, Tipo en referencia: float64
  Columna: kV, Tipo en df1: int64, Tipo en referencia: float64

Diferencias de tipo en df2:
  Columna: kV, Tipo en df2: int64, Tipo en referencia: float64
  Columna: Img Rechazadas, Tipo en df2: int64, Tipo en referencia: float64

Diferencias de tipo en df3:
  Columna: Peso[kg], Tipo en df3: int64, Tipo en referencia: float64
  Columna: kV, Tipo en df3: int64, Tipo en referencia: float64

Diferencias de tipo en df4:
  Columna: Peso[kg], Tipo en df4: object, Tipo en referencia: float64
  Columna: kV, Tipo en df4: int64, Tipo en referencia: float64
  Columna: Img Rechazadas, Tipo en df4: int64, Tipo en referencia: float64

Diferencias de tipo en df5:
  Columna: kV, Tipo en df5: int64, Tipo en referencia: float64
  Columna: Img Rechazadas, Tipo en df5: int64, Tipo en referencia: float64

In [21]:
# Convertimos los tipos para que coincidan con ref_dtypes (del df_agrupado)
to_fix = ["df1", "df2", "df3", "df4", "df5", "df_totales"]

for name in to_fix:
    d = globals()[name]
    for col, ref_dtype in ref_dtypes.items():
        if col not in d.columns:
            continue
        if "datetime64" in str(ref_dtype):
            d[col] = pd.to_datetime(d[col], errors="coerce")
        elif ref_dtype == "float64":
            d[col] = pd.to_numeric(d[col], errors="coerce").astype("float64")
        elif ref_dtype == "int64":
            # Solo si no hay NaNs; si los hubiera podríamos usar Int64 (nullable)
            if d[col].isna().any():
                d[col] = pd.to_numeric(d[col], errors="coerce").astype("Int64")
            else:
                d[col] = pd.to_numeric(d[col], errors="coerce").astype("int64")
        # object lo dejamos como está
    globals()[name] = d  # asegurar (aunque ya es in place)

# Verificación rápida
for name in to_fix:
    print(f"\n{name} dtypes:")
    print(globals()[name].dtypes)

df1 dtypes:
Fecha                      datetime64[ns]
Estudio                            object
Peso[kg]                          float64
Distancia foco-detector            object
Proyección                         object
kV                                float64
mAs                               float64
Img Aprobadas                       int64
Img Rechazadas                    float64
Dosis [mGy]                       float64
Dosis Total [mGy]                 float64
dtype: object

df2 dtypes:
Fecha                      datetime64[ns]
Estudio                            object
Peso[kg]                          float64
Distancia foco-detector            object
Proyección                         object
kV                                float64
mAs                               float64
Img Aprobadas                       int64
Img Rechazadas                    float64
Dosis [mGy]                       float64
Dosis Total [mGy]                 float64
dtype: object

df3 dtypes:
Fecha                      datetime64[ns]
Estudio                            object
Peso[kg]                          float64
Distancia foco-detector            object
Proyección                         object
kV                                float64
mAs                               float64
Img Aprobadas                       int64
Img Rechazadas                    float64
Dosis [mGy]                       float64
Dosis Total [mGy]                 float64
dtype: object

df4 dtypes:
Fecha                      datetime64[ns]
Estudio                            object
Peso[kg]                          float64
Distancia foco-detector            object
Proyección                         object
kV                                float64
mAs                               float64
Img Aprobadas                       int64
Img Rechazadas                    float64
Dosis [mGy]                       float64
Dosis Total [mGy]                 float64
dtype: object

df5 dtypes:
Fecha                      datetime64[ns]
Estudio                            object
Peso[kg]                          float64
Distancia foco-detector            object
Proyección                         object
kV                                float64
mAs                               float64
Img Aprobadas                       int64
Img Rechazadas                    float64
Dosis [mGy]                       float64
Dosis Total [mGy]                 float64
dtype: object

df_totales dtypes:
Fecha                      datetime64[ns]
Estudio                            object
Peso[kg]                          float64
Distancia foco-detector            object
Proyección                         object
kV                                float64
mAs                               float64
Img Aprobadas                       int64
Img Rechazadas                    float64
Dosis [mGy]                       float64
Dosis Total [mGy]                 float64
dtype: object

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1804942543.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#imprime la info() de cada df
print("Info df1:")
print(df1.info())
print("Info df2:")
print(df2.info())
print("Info df3:")
print(df3.info())
print("Info df4:")
print(df4.info())
print("Info df5:")
print(df5.info())
print("Info df_agrupado:")
print(df_agrupado.info())

#verificamos si todos los df tienen el mismo numero de columnas y el mismo tipo de datos, si si imprimir all good
if all(df.shape[1] == df_agrupado.shape[1] for df in [df1, df2, df3, df4, df5]) and all(df.dtypes.equals(df_agrupado.dtypes) for df in [df1, df2, df3, df4, df5]):
    print("All good")

Info df1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    113 non-null    datetime64[ns]
 1   Estudio                  113 non-null    object
 2   Peso[kg]                 113 non-null    float64
 3   Distancia foco-detector  113 non-null    object
 4   Proyección               113 non-null    object
 5   kV                       113 non-null    float64
 6   mAs                      113 non-null    float64
 7   Img Aprobadas            113 non-null    int64
 8   Img Rechazadas           104 non-null    float64
 9   Dosis [mGy]              113 non-null    float64
 10  Dosis Total [mGy]        56 non-null     float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 9.8+ KB
None
Info df2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    71 non-null     datetime64[ns]
 1   Estudio                  71 non-null     object
 2   Peso[kg]                 71 non-null     float64
 3   Distancia foco-detector  71 non-null     object
 4   Proyección               72 non-null     object
 5   kV                       72 non-null     float64
 6   mAs                      72 non-null     float64
 7   Img Aprobadas            72 non-null     int64
 8   Img Rechazadas           72 non-null     float64
 9   Dosis [mGy]              72 non-null     float64
 10  Dosis Total [mGy]        40 non-null     float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 6.3+ KB
None
Info df3:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    268 non-null    datetime64[ns]
 1   Estudio                  268 non-null    object
 2   Peso[kg]                 268 non-null    float64
 3   Distancia foco-detector  268 non-null    object
 4   Proyección               268 non-null    object
 5   kV                       268 non-null    float64
 6   mAs                      268 non-null    float64
 7   Img Aprobadas            268 non-null    int64
 8   Img Rechazadas           267 non-null    float64
 9   Dosis [mGy]              268 non-null    float64
 10  Dosis Total [mGy]        144 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 23.2+ KB
None
Info df4:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    68 non-null     datetime64[ns]
 1   Estudio                  68 non-null     object
 2   Peso[kg]                 34 non-null     float64
 3   Distancia foco-detector  68 non-null     object
 4   Proyección               68 non-null     object
 5   kV                       68 non-null     float64
 6   mAs                      68 non-null     float64
 7   Img Aprobadas            68 non-null     int64
 8   Img Rechazadas           68 non-null     float64
 9   Dosis [mGy]              68 non-null     float64
 10  Dosis Total [mGy]        38 non-null     float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 6.0+ KB
None
Info df5:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    49 non-null     datetime64[ns]
 1   Estudio                  49 non-null     object
 2   Peso[kg]                 22 non-null     float64
 3   Distancia foco-detector  49 non-null     object
 4   Proyección               49 non-null     object
 5   kV                       49 non-null     float64
 6   mAs                      49 non-null     float64
 7   Img Aprobadas            49 non-null     int64
 8   Img Rechazadas           49 non-null     float64
 9   Dosis [mGy]              49 non-null     float64
 10  Dosis Total [mGy]        26 non-null     float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 4.3+ KB
None
Info df_agrupado:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1626 entries, 0 to 1625
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    1488 non-null   datetime64[ns]
 1   Estudio                  1488 non-null   object
 2   Peso[kg]                 1016 non-null   float64
 3   Distancia foco-detector  1491 non-null   object
 4   Proyección               1626 non-null   object
 5   kV                       1626 non-null   float64
 6   mAs                      1626 non-null   float64
 7   Img Aprobadas            1626 non-null   int64
 8   Img Rechazadas           1616 non-null   float64
 9   Dosis [mGy]              1626 non-null   float64
 10  Dosis Total [mGy]        916 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 139.9+ KB
None
All good

In [23]:
#verifica si numero de filas de cada df es es mismo del dic num_filas
for df_name, num_rows in num_filas.items():
    if len(eval(df_name)) == num_rows:
        print(f"El número de filas de {df_name} es correcto.")
    else:
        print(f"El número de filas de {df_name} es incorrecto.")

El número de filas de df1 es correcto.
El número de filas de df2 es correcto.
El número de filas de df3 es correcto.
El número de filas de df4 es correcto.

# Comparacion

In [24]:

for i, df in enumerate([df1, df2, df3, df4, df5], start=1):
    df = df[df_agrupado.columns]  # mismas columnas y orden
    merged = df.merge(df_agrupado, how="left", indicator=True)
    
    no_included = merged[merged["_merge"] == "left_only"]
    print(f"--- Registros de df{i} que NO están en df_agrupado ---")
    print(no_included.head())
    print(f"Total: {len(no_included)}\n")

--- Registros de df1 que NO están en df_agrupado ---
       Fecha  Estudio  Peso[kg] Distancia foco-detector Proyección    kV  \
0 2024-11-14  Rodilla      53.0                 Camilla      AP-PA  60.0
1 2024-11-14   Muñeca      70.0                 Camilla      AP-PA  55.0
2 2024-11-14   Muñeca      62.0                 Camilla      AP-PA  55.0
3 2024-11-14   Muñeca      62.0                 Camilla        LAT  55.0
4 2024-11-14   Muñeca      62.0                 Camilla    OBLICUO  55.0

    mAs  Img Aprobadas  Img Rechazadas  Dosis [mGy]  Dosis Total [mGy]  \
0  10.0              3             0.0         1.77               1.77
1   2.9              3             0.0         0.36               0.36
2   4.5              1             0.0         0.19                NaN
3   4.5              1             0.0         0.19                NaN
4   4.5              1             0.0         0.15               0.53

      _merge
0  left_only
1  left_only
2  left_only
3  left_only
4  left_only
Total: 113

--- Registros de df2 que NO están en df_agrupado ---
       Fecha     Estudio  Peso[kg] Distancia foco-detector Proyección    kV  \
0 2024-11-22     Tobillo      65.0                   Bucky      AP-PA  65.0
1 2024-12-11       Tórax      60.0                   Bucky      AP-PA  85.0
2 2024-12-12     Abdomen      60.0                   Bucky      AP-PA  83.0
3 2024-12-12  Col Lumbar      60.0                   Bucky      AP-PA  75.0
4 2024-12-12  Col Lumbar      60.0                   Bucky        LAT  75.0

    mAs  Img Aprobadas  Img Rechazadas  Dosis [mGy]  Dosis Total [mGy]  \
0   5.0              1             0.0         0.13               0.13
1   3.5              1             0.0         0.11               0.11
2  32.0              1             0.0         2.57                NaN
3  35.0              1             0.0         0.87                NaN
4  40.0              2             0.0         2.19               3.06

      _merge
0  left_only
1  left_only
2  left_only
3  left_only
4  left_only
Total: 72

--- Registros de df3 que NO están en df_agrupado ---
       Fecha Estudio  Peso[kg] Distancia foco-detector Proyección     kV  mAs  \
0 2024-11-25     Pie      63.0                   Bucky      AP-PA   57.0  4.5
1 2024-11-25     Pie      63.0                   Bucky        LAT   54.0  4.5
2 2024-11-26     Pie      63.0                   Bucky      AP-PA   57.0  4.5
3 2024-11-26     Pie      63.0                   Bucky        LAT   54.0  4.5
4 2024-11-26   Tórax      56.0                   Bucky      AP-PA  106.0  2.5

   Img Aprobadas  Img Rechazadas  Dosis [mGy]  Dosis Total [mGy]     _merge
0              1             0.0         0.09                NaN  left_only
1              1             0.0         0.08               0.17  left_only
2              1             0.0         0.09                NaN  left_only
3              1             0.0         0.08               0.17  left_only
4              1             0.0         0.12                NaN  left_only
Total: 268

--- Registros de df4 que NO están en df_agrupado ---
       Fecha          Estudio  Peso[kg] Distancia foco-detector Proyección  \
0 2025-03-09           Lumbar       NaN                 Camilla        LAT
1 2025-03-09           Lumbar       NaN                 Camilla    OBLICUO
2 2025-03-09  Dorsal torácica       NaN                 Camilla        LAT
3 2025-03-09  Dorsal torácica       NaN                 Camilla    OBLICUO
4 2025-03-09           Pelvis       NaN                 Camilla        LAT

     kV   mAs  Img Aprobadas  Img Rechazadas  Dosis [mGy]  Dosis Total [mGy]  \
0  70.0  30.0              1             0.0         3.54                NaN
1  70.0  60.0              1             0.0         6.67              10.21
2  70.0  30.0              1             0.0         2.90                NaN
3  70.0  60.0              1             0.0         7.40              10.30
4  70.0  30.0              1             0.0         2.75                NaN

      _merge
0  left_only
1  left_only
2  left_only
3  left_only
4  left_only
Total: 68

--- Registros de df5 que NO están en df_agrupado ---
       Fecha          Estudio  Peso[kg] Distancia foco-detector Proyección  \
0 2025-03-09           Lumbar       NaN                 Camilla        LAT
1 2025-03-09           Lumbar       NaN                 Camilla    OBLICUO
2 2025-03-09  Dorsal torácica       NaN                 Camilla        LAT
3 2025-03-09  Dorsal torácica       NaN                 Camilla    OBLICUO
4 2025-03-09           Pelvis       NaN                 Camilla        LAT

     kV   mAs  Img Aprobadas  Img Rechazadas  Dosis [mGy]  Dosis Total [mGy]  \
0  70.0  30.0              1             0.0         3.54                NaN
1  70.0  60.0              1             0.0         6.67              10.21
2  70.0  30.0              1             0.0         2.90                NaN
3  70.0  60.0              1             0.0         7.40              10.30
4  70.0  30.0              1             0.0         2.75                NaN

      _merge
0  left_only
1  left_only
2  left_only
3  left_only
4  left_only
Total: 49

# Union de todos los df

In [25]:
#Unimos todos los df en uno solo contando el df_agrupado
df_completo = pd.concat([df_agrupado, df1, df2, df3, df4, df5], ignore_index=True)
print("Numero de filas df_completo:", len(df_completo))

df_completo.info()

Numero de filas df_completo: 2196
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196 entries, 0 to 2195
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    2057 non-null   datetime64[ns]
 1   Estudio                  2057 non-null   object
 2   Peso[kg]                 1524 non-null   float64
 3   Distancia foco-detector  2060 non-null   object
 4   Proyección               2196 non-null   object
 5   kV                       2196 non-null   float64
 6   mAs                      2196 non-null   float64
 7   Img Aprobadas            2196 non-null   int64
 8   Img Rechazadas           2176 non-null   float64
 9   Dosis [mGy]              2196 non-null   float64
 10  Dosis Total [mGy]        1220 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 188.8+ KB

# Analisis de datos

### 1) Frecuencia por estudio, solo los que tienen dosis total

In [26]:
#quitamos los Nan de df_completo en la columna "Dosis Total [mGy]"
df_completo_sin_NAN = df_completo.dropna(subset=["Dosis Total [mGy]"])
# Normalizar columna Estudio
df_completo_sin_NAN["Estudio"] = df_completo_sin_NAN["Estudio"].str.strip()  # quita espacios adelante/atrás
df_completo_sin_NAN["Estudio"] = df_completo_sin_NAN["Estudio"].replace({
    "Pelvis Cadera": "Pelvis",
    "Col Lumbar": "Lumbar"
})

#grafica
orden = (df_completo_sin_NAN
         .groupby("Estudio")["Dosis Total [mGy]"]
         .median()
         .sort_values()
         .index
         .tolist())
fig = go.Figure()
fig.add_trace(go.Box(
    x=df_completo_sin_NAN["Estudio"],      # categorías (un box por Estudio)
    y=df_completo_sin_NAN["Dosis Total [mGy]"],        # valores
    name="Dosis Total [mGy]",
    boxpoints="outliers",               # muestra solo outliers (usa "all" para todos los puntos)
    boxmean=True                        # dibuja la media (usa "sd" para mostrar también ±1 SD)
))

fig.update_layout(
    title="Distribución de 'Dosis Total [mGy]' por procedimiento (boxplots)",
    xaxis_title="Estudio",
    yaxis_title="Dosis Total [mGy]",
)

# aplica el orden por mediana en el eje X (quita esta línea si no quieres reordenar)
fig.update_xaxes(categoryorder="array", categoryarray=orden)

fig.show()

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2950836063.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2950836063.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
# Contar procedimientos por estudio
conteo_estudios = df_completo_sin_NAN["Estudio"].value_counts()
# Filtrar solo los estudios con más de 10 procedimientos
conteo_filtrado = conteo_estudios[conteo_estudios >= 28]

if not conteo_filtrado.empty:
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=conteo_filtrado.index,
        y=conteo_filtrado.values,
        name="Cantidad de Procedimientos",
    ))

    fig.update_layout(
        title={
            'text': "Cantidad de Procedimientos por Estudio (solo >28)",
            'font': {'size': 24}
        },
        xaxis_title="Estudio",
        yaxis_title="Cantidad de Procedimientos",
        xaxis=dict(title_font=dict(size=20), tickfont=dict(size=16)),
        yaxis=dict(title_font=dict(size=20), tickfont=dict(size=16)),
    )

    fig.show()
else:
    print("No hay estudios con más de 28 procedimientos.")

### 2)Promedio de dosis total por estudio, solo los que tienen dosis total

In [28]:
#Al df_completo_sin_NAN nos quedamos solo con las filas donde estudio es igual a "Tórax", "Pelvis", "Rodilla", "Mano","Abdomen", "Lumbar", "Hombro", "Pie"
df_completo_sin_NAN_interes = df_completo_sin_NAN[df_completo_sin_NAN["Estudio"].isin(["Tórax", "Pelvis", "Rodilla", "Mano", "Abdomen", "Lumbar", "Hombro", "Pie"])]

In [29]:
# Filtrar para excluir el estudio "Tórax"
df_plot = df_completo_sin_NAN_interes[df_completo_sin_NAN_interes["Estudio"] != "Tórax"]

orden = (df_plot
         .groupby("Estudio")["Dosis Total [mGy]"]
         .mean()
         .sort_values()
         .index
         .tolist())
fig = go.Figure()
fig.add_trace(go.Box(
    x=df_plot["Estudio"],
    y=df_plot["Dosis Total [mGy]"],
    name="Dosis Total [mGy]",
    boxpoints="outliers",
    boxmean=True,
    customdata=np.c_[df_plot["Peso[kg]"]],
    hovertemplate=(
        "Estudio: %{x}<br>"
        "Dosis: %{y:.2f} mGy<br>"
        "Peso: %{customdata[0]:.1f} kg<extra></extra>"
    ),
))

fig.update_layout(
    title={
        'text': "Distribución de 'Dosis Total [mGy]' por procedimiento (boxplots)",
        'font': {'size': 28}
    },
    xaxis_title="Estudio",
    yaxis_title="Dosis Total [mGy]",
    xaxis=dict(title_font=dict(size=22), tickfont=dict(size=18)),
    yaxis=dict(title_font=dict(size=22), tickfont=dict(size=18)),
)
fig.update_xaxes(categoryorder="array", categoryarray=orden)
fig.show()

### Filas de los datos que se salen del boxplot:

In [30]:
# DataFrame con las filas que se salen del boxplot (outliers por estudio, regla 1.5*IQR)
df_outliers = df_completo_sin_NAN_interes.copy()
q1 = df_outliers.groupby('Estudio')['Dosis Total [mGy]'].transform(lambda s: s.quantile(0.25))
q3 = df_outliers.groupby('Estudio')['Dosis Total [mGy]'].transform(lambda s: s.quantile(0.75))
iqr = q3 - q1
upper = q3 + 1.5 * iqr
lower = q1 - 1.5 * iqr
mask_outlier = (df_outliers['Dosis Total [mGy]'] > upper) | (df_outliers['Dosis Total [mGy]'] < lower)
df_outliers_boxplot = df_outliers[mask_outlier].copy()
df_outliers_boxplot.reset_index(drop=True, inplace=True)
print(f'Total de outliers detectados: {len(df_outliers_boxplot)}')
df_outliers_boxplot.head()

Total de outliers detectados: 81

,Fecha,Estudio,Peso[kg],Distancia foco-detector,Proyección,kV,mAs,Img Aprobadas,Img Rechazadas,Dosis [mGy],Dosis Total [mGy]
0,2025-04-08,Tórax,70.0,Bucky,AP-PA,100.0,20.0,2,0.0,1.76,1.76
1,2025-04-08,Tórax,70.0,Bucky,AP-PA,100.0,20.0,2,0.0,1.76,1.76
2,2025-04-08,Hombro,76.0,Bucky,OBLICUO,75.0,16.0,2,0.0,1.87,5.21
3,2025-04-10,Tórax,125.0,Bucky,LAT,120.0,20.0,1,0.0,1.68,2.54
4,2025-04-10,Tórax,NaN,Camilla,OBLICUO,95.0,8.0,1,0.0,2.03,2.70

In [31]:
#imprime solo las filas que del estudio lumbar
df_outliers_boxplot[df_outliers_boxplot["Estudio"] == "Pie"].head(50)

,Fecha,Estudio,Peso[kg],Distancia foco-detector,Proyección,kV,mAs,Img Aprobadas,Img Rechazadas,Dosis [mGy],Dosis Total [mGy]
18,2025-05-17,Pie,72.0,Bucky,OBLICUO,49.0,100.0,1,0.0,1.50,4.37
41,2025-05-19,Pie,75.0,Bucky,OBLICUO,50.0,35.0,1,0.0,0.55,1.82
42,2025-05-19,Pie,50.0,Bucky,OBLICUO,50.0,35.0,1,0.0,0.55,1.82
66,2025-05-23,Pie,67.0,Bucky,OBLICUO,52.0,100.0,1,0.0,1.69,4.99

In [32]:


#graficamos el promedio de dosis total por estudio con boxplot
orden = (df_outliers_boxplot
         .groupby("Estudio")["Dosis Total [mGy]"]
         .mean()
         .sort_values()
         .index
         .tolist())
fig = go.Figure()
fig.add_trace(go.Box(
    x=df_outliers_boxplot["Estudio"],
    y=df_outliers_boxplot["Dosis Total [mGy]"],
    name="Dosis Total [mGy]",
    boxpoints="outliers",
    boxmean=True,
    # 👇 Pasamos el peso como customdata (alineado fila a fila)
    customdata=np.c_[df_outliers_boxplot["Peso[kg]"]],
    hovertemplate=(
        "Estudio: %{x}<br>"
        "Dosis: %{y:.2f} mGy<br>"
        "Peso: %{customdata[0]:.1f} kg<extra></extra>"
    ),
))

fig.update_layout(
    title="Distribución de 'Dosis Total [mGy]' por procedimiento (boxplots)",
    xaxis_title="Estudio",
    yaxis_title="Dosis Total [mGy]",
)
fig.update_xaxes(categoryorder="array", categoryarray=orden)
fig.show()

### 3) Promedio de dosis por estudio y proyeccion(usando dosis no dosis total)

Se toaman todos los estudios de un tipo y para cada proyeccion se calcula el promedio de Dosis

In [33]:
# Normalizar columna Estudio
df_completo["Estudio"] = df_completo["Estudio"].str.strip()
df_completo["Estudio"] = df_completo["Estudio"].replace({
    "Pelvis Cadera": "Pelvis",
    "Col Lumbar": "Lumbar"
})
df_completo_interes = df_completo[df_completo["Estudio"].isin(["Tórax", "Pelvis", "Rodilla", "Mano", "Abdomen", "Lumbar", "Hombro", "Pie"])]

# Filtrar para que en Tórax no se grafique OBLICUO
df_plot = df_completo_interes[~((df_completo_interes["Estudio"] == "Tórax") & (df_completo_interes["Proyección"] == "OBLICUO"))]

# Agrupamos por Estudio y Proyección y calculamos el promedio y el conteo de Dosis
promedios_proyeccion = (df_plot
                        .groupby(["Estudio", "Proyección"])["Dosis [mGy]"]
                        .agg(promedio="mean", n_datos="count")
                        .reset_index()
                        .sort_values(by="promedio", ascending=False))

# Graficamos los promedios por estudio y proyección, mostrando el número de datos en el hover
fig3 = go.Figure()
for proyeccion in promedios_proyeccion["Proyección"].unique():
    datos = promedios_proyeccion[promedios_proyeccion["Proyección"] == proyeccion]
    fig3.add_trace(go.Bar(
        x=datos["Estudio"],
        y=datos["promedio"],
        name=proyeccion,
        customdata=datos["n_datos"],
        hovertemplate=(
            "Estudio: %{x}<br>"
            "Proyección: " + str(proyeccion) + "<br>"
            "Promedio Dosis: %{y:.2f} mGy<br>"
            "N° de datos: %{customdata}<extra></extra>"
        )
    ))
fig3.update_layout(
    title={
        'text': "Promedio de 'Dosis [mGy]' por procedimiento y proyección",
        'font': {'size': 24}
    },
    xaxis_title="Estudio",
    yaxis_title="Promedio Dosis [mGy]",
    xaxis=dict(title_font=dict(size=20), tickfont=dict(size=16)),
    yaxis=dict(title_font=dict(size=20), tickfont=dict(size=16)),
)
fig3.show()

### 4) Dosis total por peso

In [34]:
#cuantos pesos no nulos hay y nulos

print("Número de pesos no nulos:", df_completo_sin_NAN_interes["Peso[kg]"].notna().sum())
print("Número de pesos nulos:", df_completo_sin_NAN_interes["Peso[kg]"].isna().sum())
print("Número de filas totales:", len(df_completo_sin_NAN_interes))

Número de pesos no nulos: 591
Número de pesos nulos: 256
Número de filas totales: 847

In [35]:
df_completo_sin_NAN_interes = df_completo_sin_NAN_interes.dropna(subset=["Peso[kg]"])

### Histograma de pesos conjuntos:

In [36]:


#eLIMINAMOS DEL df_completo_sin_NAN_interes LOS PESOS QUE SON nan y 0
df_completo_sin_NAN_interes = df_completo_sin_NAN_interes[df_completo_sin_NAN_interes["Peso[kg]"].notna() & (df_completo_sin_NAN_interes["Peso[kg]"] > 0)]


#Organizamos menor a mayor los valores unicos de Peso[kg] e imprimimos
pesos_unicos = sorted(df_completo_sin_NAN_interes["Peso[kg]"].unique())
print("Valores únicos de Peso[kg] (ordenados):", pesos_unicos)

#Has una distribucion con histograma de la columna Peso[kg] usando bins personalizados de 45 a 125 cada 5 kg
bins = np.arange(45, 130, 15)
fig4 = go.Figure()
fig4.add_trace(go.Histogram(
    x=df_completo_sin_NAN_interes["Peso[kg]"].dropna(),
    xbins=dict(start=45, end=125, size=15)
))
fig4.update_layout(
    title="Distribución de Peso[kg] (bins de 15 kg de 45 a 125)",
    xaxis_title="Peso[kg]",
    yaxis_title="Frecuencia",
)
fig4.show()

Valores únicos de Peso[kg] (ordenados): [45.0, 46.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 93.0, 95.0, 98.0, 99.0, 100.0, 101.0, 105.0, 110.0, 115.0, 120.0, 125.0]

In [37]:
#quiero imprimir los valores unicos de los pesos para el estudio lumbar
pesos_unicos_lumbar = sorted(df_completo_sin_NAN_interes[df_completo_sin_NAN_interes["Estudio"]=="Tórax"]["Peso[kg]"])
print("Valores únicos de Peso[kg] para el estudio torax (ordenados):", pesos_unicos_lumbar)

Valores únicos de Peso[kg] para el estudio torax (ordenados): [45.0, 45.0, 46.0, 49.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 52.0, 52.0, 54.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 55.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 56.0, 57.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 58.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 61.0, 61.0, 61.0, 61.0, 62.0, 62.0, 62.0, 62.0, 63.0, 63.0, 63.0, 63.0, 63.0, 63.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 66.0, 66.0, 66.0, 67.0, 67.0, 67.0, 67.0, 67.0, 67.0, 67.0, 67.0, 67.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 69.0, 69.0, 69.0, 69.0, 69.0, 69.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 71.0, 71.0, 71.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 73.0, 74.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 76.0, 76.0, 76.0, 76.0, 76.0, 77.0, 78.0, 78.0, 78.0, 79.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 81.0, 81.0, 83.0, 85.0, 85.0, 85.0, 85.0, 85.0, 86.0, 86.0, 86.0, 86.0, 88.0, 89.0, 90.0, 90.0, 93.0, 98.0, 99.0, 100.0, 105.0, 110.0, 110.0, 110.0, 115.0, 115.0, 115.0, 120.0, 120.0, 125.0]

In [38]:
df_completo_sin_NAN_interes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 578 entries, 0 to 2195
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Fecha                    578 non-null    datetime64[ns]
 1   Estudio                  578 non-null    object
 2   Peso[kg]                 578 non-null    float64
 3   Distancia foco-detector  578 non-null    object
 4   Proyección               578 non-null    object
 5   kV                       578 non-null    float64
 6   mAs                      578 non-null    float64
 7   Img Aprobadas            578 non-null    int64
 8   Img Rechazadas           566 non-null    float64
 9   Dosis [mGy]              578 non-null    float64
 10  Dosis Total [mGy]        578 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 54.2+ KB

## Histograma para cada estudio

Con todos los datos, sin eliminar ninguno:

In [39]:
# Diagrama de barras con número de datos en el hover por bin de peso
for estudio in df_completo_sin_NAN_interes["Estudio"].unique():
    df_estudio = df_completo_sin_NAN_interes[df_completo_sin_NAN_interes["Estudio"] == estudio].copy()
    df_estudio["Peso_bin"] = pd.cut(df_estudio["Peso[kg]"], bins=np.arange(45, 136, 15))
    # Calculamos promedio y conteo por bin
    resumen = (df_estudio.groupby("Peso_bin")
               .agg(promedio_dosis=("Dosis Total [mGy]", "mean"),
                    n_datos=("Dosis Total [mGy]", "count"))
               .reset_index())

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=resumen["Peso_bin"].astype(str),
        y=resumen["promedio_dosis"],
        name=f"Estudio: {estudio}",
        customdata=resumen["n_datos"],
        hovertemplate=("Rango de Peso: %{x}<br>"
                      "Promedio Dosis: %{y:.2f} mGy<br>"
                      "N° de datos: %{customdata}<extra></extra>")
    ))
    fig.update_layout(
        title=f"Promedio de 'Dosis Total [mGy]' por rango de Peso[kg] para estudio {estudio}",
        xaxis_title="Rango de Peso[kg]",
        yaxis_title="Promedio Dosis Total [mGy]",
    )
    fig.show()

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\2083890618.py:6: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

### Filtrando desde 45 a 90 y quitando los de 1

In [40]:
# Diagrama de barras con número de datos en el hover por bin de peso
for estudio in df_completo_sin_NAN_interes["Estudio"].unique():
    df_estudio = df_completo_sin_NAN_interes[df_completo_sin_NAN_interes["Estudio"] == estudio].copy()
    df_estudio["Peso_bin"] = pd.cut(df_estudio["Peso[kg]"], bins=np.arange(45, 136, 15))
    resumen = (df_estudio.groupby("Peso_bin")
               .agg(promedio_dosis=("Dosis Total [mGy]", "mean"),
                    n_datos=("Dosis Total [mGy]", "count"))
               .reset_index())
    resumen = resumen[resumen["n_datos"] > 1]

    # Para el estudio de Tórax, solo mostrar hasta el peso de 90
    if estudio == "Tórax":
        resumen = resumen[resumen["Peso_bin"].apply(lambda x: x.right <= 90)]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=resumen["Peso_bin"].astype(str),
        y=resumen["promedio_dosis"],
        name=f"Estudio: {estudio}",
        customdata=resumen["n_datos"],
        hovertemplate=("Rango de Peso: %{x}<br>"
                      "Promedio Dosis: %{y:.2f} mGy<br>"
                      "N° de datos: %{customdata}<extra></extra>")
    ))
    fig.update_layout(
        title={
            'text': f"Promedio de 'Dosis Total [mGy]' por rango de Peso[kg] para estudio {estudio}",
            'font': {'size': 24}
        },
        xaxis_title="Rango de Peso[kg]",
        yaxis_title="Promedio Dosis Total [mGy]",
        xaxis=dict(title_font=dict(size=24), tickfont=dict(size=16)),
        yaxis=dict(title_font=dict(size=24), tickfont=dict(size=16)),
    )
    fig.show()

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\3834420130.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

### Creación de tabla LaTeX con promedios de dosis por rango de peso

In [41]:
# Crear tabla con promedios de dosis por rango de peso para cada estudio
import pandas as pd

# Crear un diccionario para almacenar todos los datos
tabla_datos = {}

# Procesar cada estudio y extraer los promedios por rango de peso
for estudio in df_completo_sin_NAN_interes["Estudio"].unique():
    df_estudio = df_completo_sin_NAN_interes[df_completo_sin_NAN_interes["Estudio"] == estudio].copy()
    df_estudio["Peso_bin"] = pd.cut(df_estudio["Peso[kg]"], bins=np.arange(45, 136, 15))
    resumen = (df_estudio.groupby("Peso_bin")
               .agg(promedio_dosis=("Dosis Total [mGy]", "mean"),
                    n_datos=("Dosis Total [mGy]", "count"))
               .reset_index())
    resumen = resumen[resumen["n_datos"] > 1]
    
    # Para el estudio de Tórax, solo mostrar hasta el peso de 90
    if estudio == "Tórax":
        resumen = resumen[resumen["Peso_bin"].apply(lambda x: x.right <= 90)]
    
    # Crear etiquetas de rangos más legibles
    resumen["Rango_str"] = resumen["Peso_bin"].apply(
        lambda x: f"{int(x.left)}-{int(x.right)}"
    )
    
    # Guardar los datos en el diccionario
    tabla_datos[estudio] = {}
    for _, row in resumen.iterrows():
        tabla_datos[estudio][row["Rango_str"]] = {
            'promedio': row["promedio_dosis"],
            'n_datos': row["n_datos"]
        }

# Crear DataFrame para la tabla
# Primero obtenemos todos los rangos únicos
todos_rangos = set()
for estudio_data in tabla_datos.values():
    todos_rangos.update(estudio_data.keys())
todos_rangos = sorted(todos_rangos, key=lambda x: int(x.split('-')[0]))

# Crear tabla con promedios
tabla_promedios = pd.DataFrame(index=todos_rangos, columns=sorted(tabla_datos.keys()))
tabla_n_datos = pd.DataFrame(index=todos_rangos, columns=sorted(tabla_datos.keys()))

for estudio in tabla_datos:
    for rango in todos_rangos:
        if rango in tabla_datos[estudio]:
            tabla_promedios.loc[rango, estudio] = tabla_datos[estudio][rango]['promedio']
            tabla_n_datos.loc[rango, estudio] = tabla_datos[estudio][rango]['n_datos']
        else:
            tabla_promedios.loc[rango, estudio] = None
            tabla_n_datos.loc[rango, estudio] = None

print("Tabla de promedios de dosis (mGy):")
print(tabla_promedios.round(2))
print("\nTabla de número de datos:")
print(tabla_n_datos)

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Tabla de promedios de dosis (mGy):
        Abdomen    Hombro     Lumbar      Mano    Pelvis       Pie   Rodilla  \
45-60  2.025714   2.42125   7.121667  0.915714  5.266364     0.405  0.510667
60-75  7.675161  4.227879   12.53875  1.774615  7.928667  0.945333  2.448387
75-90  7.328571  4.535714  20.201429      None     8.382      None      3.56

          Tórax
45-60  0.444531
60-75  1.147798
75-90  1.769444

Tabla de número de datos:
      Abdomen Hombro Lumbar  Mano Pelvis   Pie Rodilla Tórax
45-60       7      8     12     7     11     8      15    64
60-75      31     33     24    13     30    15      31   168
75-90       7      7      7  None     15  None       4    36

C:\Users\oscar\AppData\Local\Temp\ipykernel_11796\1360063264.py:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [42]:
# Generar código LaTeX para la tabla
def generar_tabla_latex(tabla_promedios, tabla_n_datos):
    latex_code = """\\begin{table}[h]
\\centering
\\caption{Promedio de dosis total por rango de peso corporal y tipo de procedimiento radiográfico}
\\label{tab:dosis_peso}
\\begin{tabular}{|c|""" + "|c" * len(tabla_promedios.columns) + """|} 
\\hline
\\textbf{Rango de Peso (kg)} """
    
    # Agregar encabezados de columnas
    for col in tabla_promedios.columns:
        latex_code += f"& \\textbf{{{col}}} "
    latex_code += "\\\\ \\hline\n"
    
    # Agregar filas de datos
    for rango in tabla_promedios.index:
        latex_code += f"{rango} "
        for col in tabla_promedios.columns:
            promedio = tabla_promedios.loc[rango, col]
            n_datos = tabla_n_datos.loc[rango, col]
            if pd.isna(promedio) or promedio is None:
                latex_code += "& -- "
            else:
                latex_code += f"& {promedio:.2f} ({int(n_datos)}) "
        latex_code += "\\\\ \\hline\n"
    
    latex_code += """\\end{tabular}
\\begin{minipage}{\\textwidth}
\\footnotesize
\\textbf{Nota:} Los valores se presentan como promedio de dosis (mGy) con el número de procedimientos entre paréntesis. Los guiones (--) indican rangos sin datos suficientes para análisis estadístico confiable.
\\end{minipage}
\\end{table}"""
    
    return latex_code

# Generar la tabla LaTeX
latex_tabla = generar_tabla_latex(tabla_promedios, tabla_n_datos)
print("Código LaTeX para la tabla:")
print("="*50)
print(latex_tabla)

Código LaTeX para la tabla:
==================================================
\begin{table}[h]
\centering
\caption{Promedio de dosis total por rango de peso corporal y tipo de procedimiento radiográfico}
\label{tab:dosis_peso}
\begin{tabular}{|c||c|c|c|c|c|c|c|c|}
\hline
\textbf{Rango de Peso (kg)} & \textbf{Abdomen} & \textbf{Hombro} & \textbf{Lumbar} & \textbf{Mano} & \textbf{Pelvis} & \textbf{Pie} & \textbf{Rodilla} & \textbf{Tórax} \\ \hline
45-60 & 2.03 (7) & 2.42 (8) & 7.12 (12) & 0.92 (7) & 5.27 (11) & 0.41 (8) & 0.51 (15) & 0.44 (64) \\ \hline
60-75 & 7.68 (31) & 4.23 (33) & 12.54 (24) & 1.77 (13) & 7.93 (30) & 0.95 (15) & 2.45 (31) & 1.15 (168) \\ \hline
75-90 & 7.33 (7) & 4.54 (7) & 20.20 (7) & -- & 8.38 (15) & -- & 3.56 (4) & 1.77 (36) \\ \hline
\end{tabular}
\begin{minipage}{\textwidth}
\footnotesize
\textbf{Nota:} Los valores se presentan como promedio de dosis (mGy) con el número de procedimientos entre paréntesis. Los guiones (--) indican rangos sin datos suficientes para análisis estadístico confiable.
\end{minipage}
\end{table}

In [43]:
# Versión mejorada de la tabla LaTeX con mejor formato
def generar_tabla_latex_mejorada(tabla_promedios, tabla_n_datos):
    latex_code = """\\begin{table}[htbp]
\\centering
\\caption{Promedio de dosis total por rango de peso corporal según tipo de procedimiento radiográfico}
\\label{tab:dosis_peso_promedio}
\\begin{adjustbox}{width=\\textwidth}
\\begin{tabular}{@{}l*{""" + str(len(tabla_promedios.columns)) + """}{c}@{}}
\\toprule
\\textbf{Rango de Peso (kg)} """
    
    # Agregar encabezados de columnas con rotación para ahorrar espacio
    for col in tabla_promedios.columns:
        latex_code += f"& \\rotatebox{{45}}{{\\textbf{{{col}}}}} "
    latex_code += "\\\\ \\midrule\n"
    
    # Agregar filas de datos
    for rango in tabla_promedios.index:
        latex_code += f"{rango} "
        for col in tabla_promedios.columns:
            promedio = tabla_promedios.loc[rango, col]
            n_datos = tabla_n_datos.loc[rango, col]
            if pd.isna(promedio) or promedio is None:
                latex_code += "& \\textcolor{gray}{--} "
            else:
                latex_code += f"& {promedio:.2f}\\textsuperscript{{({int(n_datos)})}}"
        latex_code += "\\\\ \n"
    
    latex_code += """\\bottomrule
\\end{tabular}
\\end{adjustbox}
\\begin{minipage}{\\textwidth}
\\vspace{0.3cm}
\\footnotesize
\\textbf{Nota:} Los valores se presentan como promedio de dosis total en mGy. Los números en superíndice entre paréntesis indican el tamaño de muestra (n) para cada rango. Los guiones en gris (--) representan rangos de peso sin datos suficientes (n≤1) para establecer promedios confiables. La tabla incluye únicamente procedimientos con datos válidos de peso corporal y dosis total.
\\end{minipage}
\\end{table}

% Paquetes requeridos (agregar al preámbulo del documento):
% \\usepackage{booktabs}
% \\usepackage{adjustbox}
% \\usepackage{graphicx}
% \\usepackage{xcolor}"""
    
    return latex_code

# Generar la tabla LaTeX mejorada
latex_tabla_mejorada = generar_tabla_latex_mejorada(tabla_promedios, tabla_n_datos)
print("Código LaTeX mejorado para la tabla:")
print("="*60)
print(latex_tabla_mejorada)

Código LaTeX mejorado para la tabla:
============================================================
\begin{table}[htbp]
\centering
\caption{Promedio de dosis total por rango de peso corporal según tipo de procedimiento radiográfico}
\label{tab:dosis_peso_promedio}
\begin{adjustbox}{width=\textwidth}
\begin{tabular}{@{}l*{8}{c}@{}}
\toprule
\textbf{Rango de Peso (kg)} & \rotatebox{45}{\textbf{Abdomen}} & \rotatebox{45}{\textbf{Hombro}} & \rotatebox{45}{\textbf{Lumbar}} & \rotatebox{45}{\textbf{Mano}} & \rotatebox{45}{\textbf{Pelvis}} & \rotatebox{45}{\textbf{Pie}} & \rotatebox{45}{\textbf{Rodilla}} & \rotatebox{45}{\textbf{Tórax}} \\ \midrule
45-60 & 2.03\textsuperscript{(7)}& 2.42\textsuperscript{(8)}& 7.12\textsuperscript{(12)}& 0.92\textsuperscript{(7)}& 5.27\textsuperscript{(11)}& 0.41\textsuperscript{(8)}& 0.51\textsuperscript{(15)}& 0.44\textsuperscript{(64)}\\
60-75 & 7.68\textsuperscript{(31)}& 4.23\textsuperscript{(33)}& 12.54\textsuperscript{(24)}& 1.77\textsuperscript{(13)}& 7.93\textsuperscript{(30)}& 0.95\textsuperscript{(15)}& 2.45\textsuperscript{(31)}& 1.15\textsuperscript{(168)}\\
75-90 & 7.33\textsuperscript{(7)}& 4.54\textsuperscript{(7)}& 20.20\textsuperscript{(7)}& \textcolor{gray}{--} & 8.38\textsuperscript{(15)}& \textcolor{gray}{--} & 3.56\textsuperscript{(4)}& 1.77\textsuperscript{(36)}\\
\bottomrule
\end{tabular}
\end{adjustbox}
\begin{minipage}{\textwidth}
\vspace{0.3cm}
\footnotesize
\textbf{Nota:} Los valores se presentan como promedio de dosis total en mGy. Los números en superíndice entre paréntesis indican el tamaño de muestra (n) para cada rango. Los guiones en gris (--) representan rangos de peso sin datos suficientes (n≤1) para establecer promedios confiables. La tabla incluye únicamente procedimientos con datos válidos de peso corporal y dosis total.
\end{minipage}
\end{table}

% Paquetes requeridos (agregar al preámbulo del documento):
% \usepackage{booktabs}
% \usepackage{adjustbox}
% \usepackage{graphicx}
% \usepackage{xcolor}

In [44]:
# Versión simple y profesional para tesis
def generar_tabla_latex_simple(tabla_promedios, tabla_n_datos):
    latex_code = """\\begin{table}[htbp]
\\centering
\\caption{Dosis promedio (mGy) por rango de peso corporal según procedimiento radiográfico}
\\label{tab:dosis_promedio_peso}
\\begin{tabular}{lccccccccc}
\\hline
\\textbf{Rango de} & \\multicolumn{8}{c}{\\textbf{Procedimiento Radiográfico}} \\\\
\\textbf{Peso (kg)} & \\textbf{Abd} & \\textbf{Hom} & \\textbf{Lum} & \\textbf{Man} & \\textbf{Pel} & \\textbf{Pie} & \\textbf{Rod} & \\textbf{Tór} \\\\
\\hline"""
    
    # Agregar filas de datos
    for rango in tabla_promedios.index:
        latex_code += f"\n{rango} "
        for col in tabla_promedios.columns:
            promedio = tabla_promedios.loc[rango, col]
            n_datos = tabla_n_datos.loc[rango, col]
            if pd.isna(promedio) or promedio is None:
                latex_code += "& -- "
            else:
                latex_code += f"& {promedio:.2f} "
        latex_code += "\\\\"
    
    latex_code += """
\\hline
\\end{tabular}
\\begin{minipage}{\\textwidth}
\\vspace{0.2cm}
\\footnotesize
\\textbf{Abreviaciones:} Abd=Abdomen, Hom=Hombro, Lum=Lumbar, Man=Mano, Pel=Pelvis, Pie=Pie, Rod=Rodilla, Tór=Tórax.\\\\
\\textbf{Nota:} Valores expresados como promedio aritmético de dosis total. Los guiones (--) indican insuficiencia de datos (n≤1) para cálculo estadístico confiable.
\\end{minipage}
\\end{table}"""
    
    return latex_code

# Generar tabla simple
latex_tabla_simple = generar_tabla_latex_simple(tabla_promedios, tabla_n_datos)
print("Código LaTeX simple y profesional:")
print("="*50)
print(latex_tabla_simple)

# También crear un resumen de estadísticas para incluir en el texto
print("\n" + "="*50)
print("ESTADÍSTICAS PARA INCLUIR EN EL TEXTO:")
print("="*50)

for rango in tabla_promedios.index:
    print(f"\nRango {rango} kg:")
    datos_rango = []
    for col in tabla_promedios.columns:
        promedio = tabla_promedios.loc[rango, col]
        n_datos = tabla_n_datos.loc[rango, col]
        if not pd.isna(promedio) and promedio is not None:
            datos_rango.append((col, promedio, int(n_datos)))
    
    if datos_rango:
        # Encontrar min y max
        min_proc = min(datos_rango, key=lambda x: x[1])
        max_proc = max(datos_rango, key=lambda x: x[1])
        print(f"  - Rango de dosis: {min_proc[1]:.2f} mGy ({min_proc[0]}) a {max_proc[1]:.2f} mGy ({max_proc[0]})")
        print(f"  - Total de procedimientos: {sum([x[2] for x in datos_rango])}")
        print(f"  - Promedio general del rango: {np.mean([x[1] for x in datos_rango]):.2f} mGy")

Código LaTeX simple y profesional:
==================================================
\begin{table}[htbp]
\centering
\caption{Dosis promedio (mGy) por rango de peso corporal según procedimiento radiográfico}
\label{tab:dosis_promedio_peso}
\begin{tabular}{lccccccccc}
\hline
\textbf{Rango de} & \multicolumn{8}{c}{\textbf{Procedimiento Radiográfico}} \\
\textbf{Peso (kg)} & \textbf{Abd} & \textbf{Hom} & \textbf{Lum} & \textbf{Man} & \textbf{Pel} & \textbf{Pie} & \textbf{Rod} & \textbf{Tór} \\
\hline
45-60 & 2.03 & 2.42 & 7.12 & 0.92 & 5.27 & 0.41 & 0.51 & 0.44 \\
60-75 & 7.68 & 4.23 & 12.54 & 1.77 & 7.93 & 0.95 & 2.45 & 1.15 \\
75-90 & 7.33 & 4.54 & 20.20 & -- & 8.38 & -- & 3.56 & 1.77 \\
\hline
\end{tabular}
\begin{minipage}{\textwidth}
\vspace{0.2cm}
\footnotesize
\textbf{Abreviaciones:} Abd=Abdomen, Hom=Hombro, Lum=Lumbar, Man=Mano, Pel=Pelvis, Pie=Pie, Rod=Rodilla, Tór=Tórax.\\
\textbf{Nota:} Valores expresados como promedio aritmético de dosis total. Los guiones (--) indican insuficiencia de datos (n≤1) para cálculo estadístico confiable.
\end{minipage}
\end{table}

==================================================
ESTADÍSTICAS PARA INCLUIR EN EL TEXTO:
==================================================

Rango 45-60 kg:
  - Rango de dosis: 0.41 mGy (Pie) a 7.12 mGy (Lumbar)
  - Total de procedimientos: 132
  - Promedio general del rango: 2.39 mGy

Rango 60-75 kg:
  - Rango de dosis: 0.95 mGy (Pie) a 12.54 mGy (Lumbar)
  - Total de procedimientos: 345
  - Promedio general del rango: 4.84 mGy

Rango 75-90 kg:
  - Rango de dosis: 1.77 mGy (Tórax) a 20.20 mGy (Lumbar)
  - Total de procedimientos: 76
  - Promedio general del rango: 7.63 mGy